### ISSUE TITLE
Weird/Wrong Simulation Results

### ISSUE THREAD

**Issue by lbrtbxthd** [giovannihenriksen/Anki-Simulator#35]
Hey there, for some reason my simulation results are quite weird: 

![14062020090733](https://user-images.githubusercontent.com/66902781/84590062-94215900-ae33-11ea-9153-cb6a8851ddf0.jpg)
The deck in question has 247 review cards for today, but the simulation shows 329 cards.
Now when all the reviews are done, it still shows 69 cards being left:

![14062020114458](https://user-images.githubusercontent.com/66902781/84590224-06466d80-ae35-11ea-9aa2-3d8e7045fc66.jpg)

This number changes when I do multiple simulations, so I think somehow yesterdays cards are being taken into account. This would also explain why it shows 329 in the first picture.

If I reduce the "New cards per day" option to zero, it shows zero cards left for today. However, the simulation indicates 250 review cards for tomorrow, although only 238 cards are scheduled.

![14062020114523](https://user-images.githubusercontent.com/66902781/84590339-e5324c80-ae35-11ea-8928-b9b01d75dd0a.jpg)

Am I missing something here?
Best Regards

**Comment by giovannihenriksen** [comment]
The number shown in the simulation is not the number of unique cards you will see that day, but the number of unique repetitions it expects. Based on your retention rates, the simulator expects that you will get a few cards incorrect and they will be counted twice (or more if the simulator gets those cards incorrect again). The number of repetitions reflect your expected workload on a certain day.

Furthermore, when you complete all your cards, sometimes the simulator still shows that there are more cards left to do. These are probably cards that are buried for the next day by Anki because they are similar to your other cards shown that day. The simulator does not take this into account and still expects that you do them today. I considered implementing a feature where buried cards are postponed by the simulator as well, but this would create additional problems because there is no simple sensible implementation to know which cards will be buried by Anki the next day, or the next. So I decided to keep it that way.

Hope this helps!

**Comment by matejdro** [comment]
Any chance to include that text in the manual?

I was also a bit confused by what exactly "Number of repetitions" means
